# Steve Beal
# Project Euler problem 12 solution
# 2/4/14

# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1+2+3+4+5+6+7 = 28.
# The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55 ...
# Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1, 3
# 6: 1, 2, 3, 6
# 10: 1, 2, 5, 10
# 15: 1, 3, 5, 15
# 21: 1, 3, 7, 21
# 28: 1, 2, 4, 7, 14, 28
# We can see that 28 is the first triangle number with over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?

from utils import prime_factorize

limit = 500
old_val = 1
found = False

i = 1
while not found:
    cur_val = old_val + i + 1
    prime_factors = prime_factorize(cur_val)
    divs = 1
    for f in prime_factors:
        divs = divs * (f[1] + 1)
    if divs >= limit:
        print cur_val
        found = True
    old_val = cur_val
    i += 1
    